sudo: required
services:
  - docker

before_install:
  - docker build -t michaelkim95/react-test -f ./client/Dockerfile.dev

script:
  - docker run michaelkim95/react-test -- --coverage

after_success:
  - docker build -t michaelkim95/multi-client ./client
  - docker build -t michaelkim95/multi-nginx ./nginx
  - docker build -t michaelkim95/multi-server ./server
  - docker build -t michaelkim95/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  - docker push michaelkim95/multi-client
  - docker push michaelkim95/multi-nginx
  - docker push michaelkim95/multi-server
  - docker push michaelkim95/multi-worker