sudo: required
services:
  - docker

before_install:
  - docker build -t michaelkim95/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run michaelkim95/react-test npm test -- --coverage

after_success:
  - docker build -t michaelkim95/multi-client ./client
  - docker build -t michaelkim95/multi-nginx ./nginx
  - docker build -t michaelkim95/multi-server ./server
  - docker build -t michaelkim95/multi-worker ./worker

  - docker -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push michaelkim95/multi-client
  - docker push michaelkim95/multi-nginx
  - docker push michaelkim95/multi-server
  - docker push michaelkim95/multi-worker